# Generated by Django 4.2.6 on 2023-11-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_course_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
