# Generated by Django 4.2.6 on 2023-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video_description_video_title_alter_course_educator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_video/'),
        ),
    ]
