# Generated by Django 4.2.7 on 2023-11-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_video_youtube_url_video_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(related_name='course_videos', to='home.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_for_course', to='home.course'),
        ),
    ]
