# Generated by Django 4.2.7 on 2023-11-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course_videos_alter_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='home.course'),
        ),
    ]
