# Generated by Django 4.2.7 on 2023-11-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_course_videos_alter_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='home.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
    ]
