# Generated by Django 4.2.7 on 2023-11-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_course_videos_alter_video_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
    ]
