# Generated by Django 4.2.7 on 2023-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_users',
            field=models.IntegerField(default=0),
        ),
    ]
